version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_review_hub_api
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=:8080
    restart: unless-stopped
    networks:
      - product_review_network

networks:
  product_review_network:
    driver: bridge
